### ISSUE TITLE
Symbologie digues

### ISSUE THREAD

**Issue by nicogodet** [cquest/topen25#10]
Il manque la ligne de la digue, actuellement, seuls les transects sont visibles.

https://osm.cquest.org/topen25/#15/43.3576/-1.5564
![image](https://user-images.githubusercontent.com/39594821/106714262-e0581e00-65fb-11eb-87ed-0f29a530f3ac.png)
![image](https://user-images.githubusercontent.com/39594821/106714292-ebab4980-65fb-11eb-9a0e-b5e7a134eb14.png)

**Comment by cquest** [comment]
Corrigé !
