### ISSUE TITLE
Glacier

### ISSUE THREAD

**Issue by pyrog** [cquest/topen25#11]
Les glaciers sont actuellement rendu comme des lacs. 

Exemple : [Glacier de Rochemelon](https://osm.cquest.org/topen25/#15/45.2249/7.0648)
<img width="50%" alt="Capture d’écran 2021-02-04 à 11 33 42" src="https://user-images.githubusercontent.com/2158081/106880605-d78b4900-66dc-11eb-9933-abbd0ccbe5cf.png">

La carte IGN semble colorer les courbes de niveaux en bleu : 
<img width="50%" alt="Capture d’écran 2021-02-04 à 11 34 15" src="https://user-images.githubusercontent.com/2158081/106880663-eb36af80-66dc-11eb-917f-3d841953d7a9.png">

**Comment by bohwaz** [comment]
Rendu Top25  :  ![image](https://user-images.githubusercontent.com/584819/106887322-4b315400-66e5-11eb-8b65-7841aa496d41.png)

**Comment by cquest** [comment]
Toutes les surfaces hydro sont à compléter car pour l'instant indifférenciées

**Comment by cquest** [comment]
Les glaciers sont maintenant bien plus propres: https://osm.cquest.org/topen25/#15/45.2249/7.0648
