### ISSUE TITLE
Espacement des courbes de niveaux

### ISSUE THREAD

**Issue by pyrog** [cquest/topen25#12]
En montagne elles sont trop resserrées : 
* espacement de 5 m
* libellés des courbes directrices tous les 25 m

Exemple : [Ouille du Favre](https://osm.cquest.org/topen25/#15/45.2553/7.0971)
<img width="50%" alt="Topen25" src="https://user-images.githubusercontent.com/2158081/106882307-e7a42800-66de-11eb-861a-e4fe7b722665.png">

IGN
* espacement de 40 m
* libellés des courbes directrices tous les 200 m
<img width="50%" alt="IGN" src="https://user-images.githubusercontent.com/2158081/106882395-fa1e6180-66de-11eb-88e3-54629b62a7fb.png">

**Comment by bohwaz** [comment]
hum c'est pas la bonne carte IGN.

La top25 donne un espacement plus rapproché et plus utile : 
![image](https://user-images.githubusercontent.com/584819/106887258-3359d000-66e5-11eb-8ea3-32866c10faa1.png)

**Comment by cquest** [comment]
Donc pas de changement ?

**Comment by cquest** [comment]
Une modif de faite: courbes tous les 5m/25m puis tous les 10m/50m au dessus de 500m d'altitude.

Je vois par contre, un changement de couleur sur les glaciers... que je vais ajouter.

**Comment by cquest** [comment]
Exemple des courbes de niveau adaptatives ici: https://osm.cquest.org/topen25/#15/45.9532/5.8517

Je ferme, à réouvrir si besoin.

**Comment by bohwaz** [comment]
Sur l'exemple donné les courbes 600 et 650 sont écrites à l'envers l'une de l'autre du coup pas top pour la lecture. et ça donne un peu l'impression que c'est marqué 900.
