### ISSUE TITLE
Noms de communes pas ou mal représentés

### ISSUE THREAD

**Issue by Shot2** [cquest/topen25#8]
**Description du problème**
Le nom de certains hameaux/écarts/subdivisions d'une commune est mal ou pas affiché, faute de rendu graphique ou d'une hiérarchisation visuelle (par la taille ou graisse de police) de ce rendu.

**Exemple**
Exemples sur le territoire de la commune nouvelle de Mauges-sur-Loire :
- Montjean-sur-Loire (commune déléguée) ne semble pas indiqué : https://osm.cquest.org/topen25/#15/47.3857/-0.8574
- Saint-Laurent-du-Mottay (commune déléguée) ne semble pas indiqué : https://osm.cquest.org/topen25/#15/47.3512/-0.9500
- Le Mesnil-en-Vallée (commune déléguée) est indiqué, mais avec un rendu ne permettant pas de différencier d'un simple quartier ou lieu-dit : https://osm.cquest.org/topen25/#15/47.3660/-0.9342

**La correction souhaitée**
S'assurer que les toponymes majeurs sont représentés (ou non-représentés pour raisons de place) en suivant une hiérarchisation (p.ex. : communes > communes déléguées > hameaux/écarts > quartiers > autres toponymes)

**Comment by cquest** [comment]
Les noms des communes déléguées sont désormais rendus séparément, avant les autres toponymes.
