### ISSUE TITLE
Hiérarchisation des toponymes bâti (résidences/immeubles)

### ISSUE THREAD

**Issue by gendy54** [cquest/topen25#9]
**Description du problème**
Les noms de résidences/immeubles apparaissent sur le fond carto, gênant la lisibilité.

**Exemple**
- https://osm.cquest.org/topen25/#15/48.6803/6.1493
- https://osm.cquest.org/topen25/#15/48.7102/6.2007
- https://osm.cquest.org/topen25/#15/48.6992/6.2122

**La correction souhaitée**
Suppression de ces infos bâtimentaires qui n'apportent rien dans le contexte du 1/25000e.
Permettra sûrement à des infos plus pertinentes d'avoir de la place pour être affichées.

**Comment by bohwaz** [comment]
Hum pas complètement d'accord, je trouve cette info utile en milieu urbain :)

**Comment by Shot2** [comment]
bohwaz > Pour ce genre d'infos, il vaut mieux passer à des échelles supérieures (disons L17-19 pour avoir îlots urbains, numéros de rue, parcellaire...)

**Comment by gendy54** [comment]
Je parle uniquement à ce niveau de zoom, hein ;)

**Comment by cquest** [comment]
Les "Immeuble xxxx" ne sont plus rendus.
Le reste est hiérarchisé par une taille de texte décroissante.
